apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: CECNBTransformer
  labels: 
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  directoryDetect:
    levels: -1
  consumes:
    CNBDetectedService:
      merge: false
  config:
    starFile: "cecnb.star"