apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: CEDockerFileTransformer
  labels: 
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  directoryDetect:
    levels: -1
  consumes:
    DockerfileForService:
      merge: false
  config:
    starFile: "cedockerfile.star"