apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: IKSKubernetes
  labels:
    move2kube.konveyor.io/built-in: false
spec:
  class: "Kubernetes"
  directoryDetect:
    levels: 0
  consumes:
    IR:
      merge: true
  produces:
    KubernetesYamls:
      disabled: false
  override:
    matchLabels: 
      move2kube.konveyor.io/name: Kubernetes
  dependency:
    matchLabels:
      move2kube.konveyor.io/name: IKSClusterSelector
  config:
    outputPath: "deploy/yamls/iks"
    ingressName: "{{ .ProjectName }}"
